1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [1]:
import numpy as np

a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [7]:
a = np.random.randint(1, 11, size=(5,5))
print(a)

[[ 5  5  9  3  3]
 [10  3  1  2 10]
 [ 1  2  3  9  6]
 [ 5  2  7 10  6]
 [10  1  8  9  8]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [9]:
a = np.random.rand(4, 4)
print(a)

[[0.35017189 0.11556356 0.58742286 0.79683937]
 [0.44591714 0.04699914 0.92808492 0.96009914]
 [0.58988244 0.7883935  0.84230673 0.79112141]
 [0.25338281 0.4760185  0.52406764 0.78428815]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [10]:
a = np.random.randint(1, 11, size=(5,))
b = np.random.randint(1, 11, size=(5,))
print('a:', a)
print('b:', b)
print('a + b:', a + b)
print('a - b:', a - b)
print('a * b:', a * b)

a: [3 9 6 3 6]
b: [4 2 7 1 8]
a + b: [ 7 11 13  4 14]
a - b: [-1  7 -1  2 -2]
a * b: [12 18 42  3 48]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [11]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([8, 9, 10, 11, 12, 13, 14])
print(np.dot(a, b))

336


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [14]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
print(a)
print(b)
print(np.dot(a, b))

[[6 7]
 [7 4]]
[[10  4  4]
 [ 2  4  4]]
[[74 52 52]
 [78 44 44]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [20]:
a = np.random.randint(1, 11, size=(3, 3))
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)

[[9 2 6]
 [7 8 8]
 [3 8 5]]
[[ 0.52173913 -0.82608696  0.69565217]
 [ 0.23913043 -0.58695652  0.65217391]
 [-0.69565217  1.43478261 -1.26086957]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [21]:
a = np.random.rand(4, 4)
print(a)
print(a.T)

[[0.62738044 0.38952063 0.81919085 0.71968272]
 [0.36253936 0.9282525  0.87467182 0.61937653]
 [0.03801788 0.28955876 0.02227915 0.57814876]
 [0.63514211 0.12370185 0.51520507 0.87952126]]
[[0.62738044 0.36253936 0.03801788 0.63514211]
 [0.38952063 0.9282525  0.28955876 0.12370185]
 [0.81919085 0.87467182 0.02227915 0.51520507]
 [0.71968272 0.61937653 0.57814876 0.87952126]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [22]:
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
print(a)
print(b)
print(np.dot(a, b))

[[1 9 4 3]
 [8 3 7 8]
 [5 8 6 4]]
[ 8 10  6  4]
[134 168 172]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [23]:
a = np.random.rand(2, 3)
b = np.random.rand(3)
print(a)
print(b)
print(np.dot(a, b))

[[0.32427984 0.6909454  0.1489573 ]
 [0.94419814 0.6878715  0.13459023]]
[0.70000764 0.23962483 0.84987507]
[0.51916114 0.94016189]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [24]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(a)
print(b)
print(a * b)

[[2 1]
 [3 3]]
[[1 7]
 [8 3]]
[[ 2  7]
 [24  9]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [25]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(a)
print(b)
print(np.dot(a, b))

[[3 9]
 [4 3]]
[[3 9]
 [9 2]]
[[90 45]
 [39 42]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [26]:
a = np.random.randint(1, 101, size=(5, 5))
print(a)
print(a.sum())

[[58  8 23  4 64]
 [31 27 55 43 51]
 [ 3 40 50 30 14]
 [94 91 16 91 14]
 [86 65 60  3 20]]
1041


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [27]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print(a)
print(b)
print(a - b)

[[ 1  5 10  9]
 [ 7  6  5  7]
 [ 8  1  1  4]
 [ 3  9  8  8]]
[[ 6  3  9 10]
 [ 5 10  8 10]
 [ 3  7  6  5]
 [ 9  1  6  3]]
[[-5  2  1 -1]
 [ 2 -4 -3 -3]
 [ 5 -6 -5 -1]
 [-6  8  2  5]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [29]:
a = np.random.rand(3, 3)
b = np.sum(a, axis=1)
print(a)
print(b)

[[0.87709857 0.05521746 0.476958  ]
 [0.12116033 0.12283477 0.74040876]
 [0.02999084 0.23563142 0.11392024]]
[1.40927402 0.98440386 0.3795425 ]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих чисел.

In [32]:
a = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])
b = np.square(a)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [33]:
a = np.random.randint(1, 51, size=4)
b = np.sqrt(a)
print(a)
print(b)

[31  5  8 42]
[5.56776436 2.23606798 2.82842712 6.4807407 ]
